// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://bhnjpyroylvratzqiknv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJobmpweXJveWx2cmF0enFpa252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzMzI2MTYsImV4cCI6MjA4ODkwODYxNn0.jsHE2fvQZUQN-4vrFgS4v1pZwwWYD8Tb5Z5fyWPR0ws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const fetchNoCache: typeof fetch = (input, init: RequestInit = {}) => {
  // Supabase passes a Headers object; we must preserve it to keep the `apikey` header.
  const headers = new Headers(init.headers);
  headers.set('Cache-Control', 'no-cache, no-store, max-age=0');

  return fetch(input, {
    ...init,
    cache: 'no-store',
    headers,
  });
};

export const supabase = createClient<Database, 'public'>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Ensure guest views always fetch the latest data from Supabase.
  global: {
    fetch: fetchNoCache,
  },
});